spring:
    profiles:
        include: db

mysql:
      url: jdbc:mysql://localhost:3306/zhjg_0909?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
#     url: jdbc:mysql://10.1.2.33:3306/cleanse_db?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#     username: cleanse_sys
#     password: cleanse_sys

#logPath: E:/0729/demo_logs
