spring:
    profiles:
        include: db

mysql:
    url: jdbc:mysql://172.20.10.69:3306/zhjg?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

hive:
    user: hdfs
    password:
    url: jdbc:hive2://172.20.10.16:10000/zhjg
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    filters: stat
    initialSize: 2
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 500

#连接远程服务器配置
ssh:
#    host: 10.1.3.239
#    port: 22
#    user: root
#    pass: 123456
    url: http://172.20.10.16:8082/
